// Nombres válidos del sistema de iconos.
// Vive fuera de Icon.astro porque el compilador de Astro no admite
// declaraciones `export type` dentro del frontmatter de un componente.

export type IconName =
  // — interfaz —
  | "check"
  | "arrow-right"
  | "arrow-up-right"
  | "plus"
  | "close"
  | "menu"
  | "minus"
  | "globe"
  | "sun"
  | "moon"
  // — capacidades / servicios —
  | "layout"
  | "target"
  | "settings"
  | "pen"
  | "map-pin"
  | "sparkles"
  | "trending-up"
  | "workflow"
  | "search"
  | "zap"
  | "shield"
  | "smartphone"
  | "link"
  | "message-circle"
  | "file-text"
  | "calendar"
  | "database"
  | "mail"
  | "bar-chart"
  | "repeat"
  | "users"
  | "clipboard-check"
  | "briefcase"
  | "calculator"
  | "scale"
  | "receipt"
  | "building"
  | "phone"
  | "star"
  | "lock"
  | "cpu"
  | "diamond"
  | "handshake"
  | "route"
  | "megaphone"
  // — marcas —
  | "whatsapp"
  | "instagram"
  | "linkedin"
  | "facebook"
  | "google";
